### ISSUE TITLE
 Build Web Apps with Pyramid: Part 1: PyCharm Demo - App will not run

### ISSUE THREAD

**Issue by ianmonat** [mikeckennedy/python-for-entrepreneurs-course-demos#3]
Hi Michael, 

I'm on a windows machine, running PyCharm Pro (free trial), and I created a venv that did not offer 'None' as a Template Language setting, the only options are Django and Jinja2. 

![template settings](https://cloud.githubusercontent.com/assets/20530405/23333878/ac00cebc-fb48-11e6-8f3a-a233772273e2.JPG)

I mention that in case it has to do with the error message I got when I tried to run the app. 

C:\Users\imonat\Desktop\Python_Scripts\blueyellow_pycharm_app\development.ini
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pycharm\pycharm_load_entry_point.py", line 12, in <module>
    sys.exit(f())
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\scripts\pserve.py", line 40, in main
    return command.run()
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\scripts\pserve.py", line 210, in run
    setup_logging(config_path, global_conf=vars)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\scripts\common.py", line 34, in setup_logging
    parser.read([path])
  File "C:\Users\imonat\AppData\Local\Programs\Python\Python35-32\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Users\imonat\AppData\Local\Programs\Python\Python35-32\lib\configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'C:\\Users\\imonat\\Desktop\\Python_Scripts\\blueyellow_pycharm_app\\development.ini' [line 15]: option 'pyramid.includes' in section 'app:main' already exists

Process finished with exit code 1

Can you interpret the cause of the error? I'm not understanding what it wants. I was able to get the app to run using the cmd line, but love how much faster Pycharm is, just need to get it running! Thank you for your help!

**Comment by danshorstein** [comment]
I ran into the same error message, seems to be a bug in Pycharm. The
Develoment.ini file includes two "pyramid.includes" statements, and you
have to move the pyramid_debugtoolbar up from the second one - see
http://stackoverflow.com/questions/36941351/getting-configparser-duplicateoptionerror-option-pyramid-includes-in-section

**Comment by ianmonat** [comment]
Thanks Dan - I made the change per your recommendation but unfortunately it seems the error grew!


![capture](https://cloud.githubusercontent.com/assets/20530405/23334589/dbeff8ce-fb56-11e6-8097-e4ed2beef925.JPG)

C:\Users\imonat\blueyellowpy\Scripts\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pycharm\pycharm_load_entry_point.py" C:\Users\imonat\Desktop\Python_Scripts\blueyellow_pycharm_app\development.ini
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pycharm\pycharm_load_entry_point.py", line 12, in <module>
    sys.exit(f())
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\scripts\pserve.py", line 40, in main
    return command.run()
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\scripts\pserve.py", line 222, in run
    app_spec, name=app_name, relative_to=base, global_conf=vars)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\paste\deploy\loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\paste\deploy\loadwsgi.py", line 272, in loadobj
    return context.create()
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\paste\deploy\loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\paste\deploy\loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\paste\deploy\util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "C:\Users\imonat\Desktop\Python_Scripts\blueyellow_pycharm_app\blueyellow_pycharm_app\__init__.py", line 7, in main
    config = Configurator(settings=settings)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\config\__init__.py", line 329, in __init__
    exceptionresponse_view=exceptionresponse_view,
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\config\__init__.py", line 446, in setup_registry
    self.include(inc)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\config\__init__.py", line 776, in include
    c = self.maybe_dotted(callable)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\config\__init__.py", line 876, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\path.py", line 320, in maybe_resolve
    return self._resolve(dotted, package)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "C:\Users\imonat\blueyellowpy\lib\site-packages\pyramid\path.py", line 376, in _zope_dottedname_style
    found = __import__(used)
ImportError: No module named 'pyramid_django'

Process finished with exit code 1

**Comment by danshorstein** [comment]
in development.ini I just replaced "pyramid_django" with
"pyramid_chameleon" - I think you have to do it in setup.py also.

Stupid windows!



[image: pasted1]
Try that and see if it helps!

**Comment by ianmonat** [comment]
It worked! Thanks so much for your help. Onward and upward.
![capture1](https://cloud.githubusercontent.com/assets/20530405/23334955/feb02c78-fb5e-11e6-90e3-78f6e5ea9378.JPG)
